# Generated by Django 4.1.3 on 2022-12-05 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table_Ch4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('exercise', models.CharField(max_length=120)),
                ('time', models.TimeField()),
                ('grade', models.IntegerField()),
                ('examiner', models.CharField(max_length=50)),
            ],
        ),
    ]
