# Generated by Django 4.1.3 on 2022-12-05 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table_ch4',
            name='date',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='table_ch4',
            name='time',
            field=models.CharField(max_length=5),
        ),
    ]
