# Generated by Django 4.1.3 on 2022-12-16 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_book', '0003_table_ch5'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Table_Ch4',
            new_name='TableCh4',
        ),
        migrations.RenameModel(
            old_name='Table_Ch5',
            new_name='TableCh5',
        ),
    ]
