# Generated by Django 4.1.3 on 2022-12-17 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_book', '0005_tablech1'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableCh2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.CharField(max_length=50)),
            ],
        ),
    ]
