# Generated by Django 4.1.3 on 2022-12-18 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_book', '0006_tablech2'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableCh8',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=11)),
                ('type', models.CharField(max_length=10)),
                ('times_of_day', models.CharField(max_length=10)),
                ('flight_permit', models.CharField(max_length=100)),
                ('meteo_height', models.PositiveSmallIntegerField()),
                ('meteo_vis', models.PositiveSmallIntegerField()),
                ('meteo_wind', models.PositiveSmallIntegerField()),
                ('examiner', models.CharField(max_length=70)),
            ],
        ),
    ]
