# Generated by Django 4.1.3 on 2022-12-18 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_book', '0007_tablech8'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableCh9',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('characteristic', models.TextField()),
            ],
        ),
    ]
