# Generated by Django 4.1.3 on 2022-12-19 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_book', '0008_tablech9'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableCh10',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=11)),
                ('remarks', models.TextField()),
                ('examiner', models.CharField(max_length=70)),
                ('deletion_mark', models.CharField(max_length=100)),
            ],
        ),
    ]
