# Generated by Django 4.1.3 on 2022-12-22 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_book', '0009_tablech10'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableCh6',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=11)),
                ('type', models.CharField(max_length=10)),
                ('exercise', models.CharField(max_length=120)),
                ('quantity_approach', models.PositiveSmallIntegerField()),
                ('quantity_landing', models.PositiveSmallIntegerField()),
                ('time_hours', models.PositiveSmallIntegerField()),
                ('time_mins', models.PositiveSmallIntegerField()),
                ('instrumental_time_hours', models.PositiveSmallIntegerField()),
                ('instrumental_time_mins', models.PositiveSmallIntegerField()),
                ('extra_time_hours', models.PositiveSmallIntegerField()),
                ('extra_time_mins', models.PositiveSmallIntegerField()),
                ('captain_hours', models.PositiveSmallIntegerField()),
                ('captain_mins', models.PositiveSmallIntegerField()),
                ('captain_route_hours', models.PositiveSmallIntegerField()),
                ('captain_route_mins', models.PositiveSmallIntegerField()),
                ('captain_night_hours', models.PositiveSmallIntegerField()),
                ('captain_night_mins', models.PositiveSmallIntegerField()),
                ('grade', models.PositiveSmallIntegerField()),
                ('examiner', models.CharField(max_length=50)),
            ],
        ),
    ]
