# Generated by Django 4.1.3 on 2023-01-16 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_book', '0014_tablech730_tablech731_tablech732_tablech733_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableCh740',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate', models.CharField(max_length=100)),
                ('type_n_number', models.CharField(max_length=35)),
                ('aerodrome', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=10)),
                ('time', models.CharField(max_length=5)),
                ('sum_time', models.CharField(max_length=5)),
                ('result', models.CharField(max_length=20)),
                ('examiner', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='TableCh741',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preparation', models.CharField(max_length=1)),
                ('inspection', models.CharField(max_length=1)),
                ('startup', models.CharField(max_length=1)),
                ('takeoff', models.CharField(max_length=1)),
                ('circle_flight', models.CharField(max_length=1)),
                ('landing', models.CharField(max_length=1)),
                ('approach', models.CharField(max_length=1)),
                ('missed_approach', models.CharField(max_length=1)),
                ('radio_failure', models.CharField(max_length=1)),
                ('eng_failure', models.CharField(max_length=1)),
                ('attestation', models.CharField(max_length=15)),
                ('examiner', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='TableCh742',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attestation', models.CharField(max_length=10)),
                ('recommendations', models.CharField(max_length=200)),
                ('signature', models.ImageField(upload_to='')),
                ('examiner', models.CharField(max_length=60)),
                ('license_num', models.CharField(max_length=10)),
                ('date', models.CharField(max_length=10)),
            ],
        ),
    ]
