# Generated by Django 4.1.3 on 2023-01-17 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_book', '0016_tablech750_tablech751_tablech752_tablech753_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableCh760',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate', models.CharField(max_length=100)),
                ('type_n_number', models.CharField(max_length=35)),
                ('aerodrome', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=10)),
                ('time', models.CharField(max_length=5)),
                ('sum_time', models.CharField(max_length=5)),
                ('result', models.CharField(max_length=20)),
                ('examiner', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='TableCh761',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preparation', models.CharField(max_length=1)),
                ('knowledge', models.CharField(max_length=1)),
                ('startup_prep', models.CharField(max_length=1)),
                ('before_takeoff', models.CharField(max_length=1)),
                ('attestation', models.CharField(max_length=15)),
                ('examiner', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='TableCh762',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard_maneuvers', models.CharField(max_length=1)),
                ('turns', models.CharField(max_length=1)),
                ('stall', models.CharField(max_length=1)),
                ('no_eng_landing', models.CharField(max_length=1)),
                ('emerg_landing', models.CharField(max_length=1)),
                ('emerg_situation', models.CharField(max_length=1)),
                ('circle_entering', models.CharField(max_length=1)),
                ('attestation', models.CharField(max_length=15)),
                ('examiner', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='TableCh763',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('takeoff', models.CharField(max_length=1)),
                ('eng_failure', models.CharField(max_length=1)),
                ('circle_flight', models.CharField(max_length=1)),
                ('circle_low_alt', models.CharField(max_length=1)),
                ('app_n_landing', models.CharField(max_length=1)),
                ('short_rw', models.CharField(max_length=1)),
                ('missed_approach', models.CharField(max_length=1)),
                ('attestation', models.CharField(max_length=15)),
                ('examiner', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='TableCh764',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attestation', models.CharField(max_length=10)),
                ('recommendations', models.CharField(max_length=200)),
                ('signature', models.ImageField(upload_to='')),
                ('examiner', models.CharField(max_length=60)),
                ('license_num', models.CharField(max_length=10)),
                ('date', models.CharField(max_length=10)),
            ],
        ),
    ]
