# Generated by Django 4.1.3 on 2023-01-18 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_book', '0017_tablech760_tablech761_tablech762_tablech763_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableCh770',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate', models.CharField(max_length=100)),
                ('type_n_number', models.CharField(max_length=35)),
                ('aerodrome', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=10)),
                ('time', models.CharField(max_length=5)),
                ('sum_time', models.CharField(max_length=5)),
                ('result', models.CharField(max_length=20)),
                ('examiner', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='TableCh771',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preparation', models.CharField(max_length=1)),
                ('pref_inspection', models.CharField(max_length=1)),
                ('deck_check', models.CharField(max_length=1)),
                ('pref_proc', models.CharField(max_length=1)),
                ('attestation', models.CharField(max_length=15)),
                ('examiner', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='TableCh772',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turns30', models.CharField(max_length=1)),
                ('spirals', models.CharField(max_length=1)),
                ('turns45', models.CharField(max_length=1)),
                ('maneuvering', models.CharField(max_length=1)),
                ('attestation', models.CharField(max_length=15)),
                ('examiner', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='TableCh773',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('climb_n_descent', models.CharField(max_length=1)),
                ('stby_spirals', models.CharField(max_length=1)),
                ('stby_maneuvering', models.CharField(max_length=1)),
                ('compl_spatial_pos', models.CharField(max_length=1)),
                ('attestation', models.CharField(max_length=15)),
                ('examiner', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='TableCh774',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('takeoff_n_land', models.CharField(max_length=1)),
                ('nav_operating', models.CharField(max_length=1)),
                ('radio', models.CharField(max_length=1)),
                ('eng_operating', models.CharField(max_length=1)),
                ('attestation', models.CharField(max_length=15)),
                ('examiner', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='TableCh775',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attestation', models.CharField(max_length=10)),
                ('recommendations', models.CharField(max_length=200)),
                ('signature', models.ImageField(upload_to='')),
                ('examiner', models.CharField(max_length=60)),
                ('license_num', models.CharField(max_length=10)),
                ('date', models.CharField(max_length=10)),
            ],
        ),
    ]
