# Generated by Django 4.1.3 on 2023-01-19 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_book', '0018_tablech770_tablech771_tablech772_tablech773_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableCh780',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate', models.CharField(max_length=100)),
                ('type_n_number', models.CharField(max_length=35)),
                ('aerodrome', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=10)),
                ('time', models.CharField(max_length=5)),
                ('sum_time', models.CharField(max_length=5)),
                ('result', models.CharField(max_length=20)),
                ('examiner', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='TableCh781',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planning', models.CharField(max_length=1)),
                ('inspection', models.CharField(max_length=1)),
                ('startup', models.CharField(max_length=1)),
                ('ATC_clearance', models.CharField(max_length=1)),
                ('takeoff', models.CharField(max_length=1)),
                ('airway_entering', models.CharField(max_length=1)),
                ('attestation', models.CharField(max_length=15)),
                ('examiner', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='TableCh782',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintaining_track', models.CharField(max_length=1)),
                ('flightplan', models.CharField(max_length=1)),
                ('reports', models.CharField(max_length=1)),
                ('instrumental_flight', models.CharField(max_length=1)),
                ('attestation', models.CharField(max_length=15)),
                ('examiner', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='TableCh783',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hold_area_entering', models.CharField(max_length=1)),
                ('accuracy_hold_area', models.CharField(max_length=1)),
                ('maintaining_alt', models.CharField(max_length=1)),
                ('wind_correction', models.CharField(max_length=1)),
                ('hold_area_leaving', models.CharField(max_length=1)),
                ('attestation', models.CharField(max_length=15)),
                ('examiner', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='TableCh784',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_stage', models.CharField(max_length=1)),
                ('landing_course', models.CharField(max_length=1)),
                ('ILS_established', models.CharField(max_length=1)),
                ('decision_alt', models.CharField(max_length=1)),
                ('missed_approach', models.CharField(max_length=1)),
                ('attestation', models.CharField(max_length=15)),
                ('examiner', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='TableCh785',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_stage', models.CharField(max_length=1)),
                ('landing_course', models.CharField(max_length=1)),
                ('final_stage', models.CharField(max_length=1)),
                ('decision_alt', models.CharField(max_length=1)),
                ('missed_approach', models.CharField(max_length=1)),
                ('attestation', models.CharField(max_length=15)),
                ('examiner', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='TableCh786',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation', models.CharField(max_length=1)),
                ('flight_info', models.CharField(max_length=1)),
                ('radio', models.CharField(max_length=1)),
                ('IFR_knowledge', models.CharField(max_length=1)),
                ('briefing', models.CharField(max_length=1)),
                ('attestation', models.CharField(max_length=15)),
                ('examiner', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='TableCh787',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attestation', models.CharField(max_length=10)),
                ('dateIFT07', models.CharField(max_length=10)),
                ('recommendations', models.CharField(max_length=200)),
                ('signature', models.ImageField(upload_to='')),
                ('examiner', models.CharField(max_length=60)),
                ('license_num', models.CharField(max_length=10)),
                ('date', models.CharField(max_length=10)),
            ],
        ),
    ]
