# Generated by Django 4.1.3 on 2023-01-21 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_book', '0021_tablech7100_tablech7101_tablech7102'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableCh7110',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate', models.CharField(max_length=100)),
                ('type_n_number', models.CharField(max_length=35)),
                ('aerodrome', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=10)),
                ('time', models.CharField(max_length=5)),
                ('sum_time', models.CharField(max_length=5)),
                ('result', models.CharField(max_length=20)),
                ('examiner', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='TableCh7111',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preparation', models.CharField(max_length=1)),
                ('inspection', models.CharField(max_length=1)),
                ('startup', models.CharField(max_length=1)),
                ('attestation', models.CharField(max_length=15)),
                ('examiner', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='TableCh7112',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('takeoff', models.CharField(max_length=1)),
                ('landing', models.CharField(max_length=1)),
                ('eng_failure', models.CharField(max_length=1)),
                ('one_eng_landing', models.CharField(max_length=1)),
                ('attestation', models.CharField(max_length=15)),
                ('examiner', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='TableCh7113',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airway_entrance', models.CharField(max_length=1)),
                ('airway_navigation', models.CharField(max_length=1)),
                ('hold_area', models.CharField(max_length=1)),
                ('precision_app', models.CharField(max_length=1)),
                ('nonprecision_app', models.CharField(max_length=1)),
                ('missed_approach', models.CharField(max_length=1)),
                ('low_alt_circle', models.CharField(max_length=1)),
                ('attestation', models.CharField(max_length=15)),
                ('examiner', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='TableCh7114',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('radio', models.CharField(max_length=1)),
                ('observation', models.CharField(max_length=1)),
                ('visual_maneuvering', models.CharField(max_length=1)),
                ('team_work', models.CharField(max_length=1)),
                ('missed_approach', models.CharField(max_length=1)),
                ('emergency', models.CharField(max_length=1)),
                ('attestation', models.CharField(max_length=15)),
                ('examiner', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='TableCh7115',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attestation', models.CharField(max_length=10)),
                ('dateGHT06', models.CharField(max_length=10)),
                ('dateIRT08', models.CharField(max_length=10)),
                ('dateMET09', models.CharField(max_length=10)),
                ('dateMET10', models.CharField(max_length=10)),
                ('recommendations', models.CharField(max_length=200)),
                ('signature', models.ImageField(upload_to='')),
                ('examiner', models.CharField(max_length=60)),
                ('license_num', models.CharField(max_length=10)),
                ('date', models.CharField(max_length=10)),
            ],
        ),
    ]
