# Generated by Django 4.1.3 on 2023-02-06 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_book', '0022_tablech7110_tablech7111_tablech7112_tablech7113_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tablech1',
            name='instructor4',
        ),
    ]
