# Generated by Django 4.1.3 on 2023-02-23 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_book', '0023_remove_tablech1_instructor4'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablech8',
            name='meteo_height',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tablech8',
            name='meteo_vis',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tablech8',
            name='meteo_wind',
            field=models.CharField(max_length=100),
        ),
    ]
