# Generated by Django 4.1.3 on 2023-02-25 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_book', '0024_alter_tablech8_meteo_height_alter_tablech8_meteo_vis_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tablech7102',
            name='signature',
        ),
        migrations.RemoveField(
            model_name='tablech7115',
            name='signature',
        ),
        migrations.RemoveField(
            model_name='tablech717',
            name='signature',
        ),
        migrations.RemoveField(
            model_name='tablech725',
            name='signature',
        ),
        migrations.RemoveField(
            model_name='tablech735',
            name='signature',
        ),
        migrations.RemoveField(
            model_name='tablech742',
            name='signature',
        ),
        migrations.RemoveField(
            model_name='tablech756',
            name='signature',
        ),
        migrations.RemoveField(
            model_name='tablech764',
            name='signature',
        ),
        migrations.RemoveField(
            model_name='tablech775',
            name='signature',
        ),
        migrations.RemoveField(
            model_name='tablech787',
            name='signature',
        ),
        migrations.RemoveField(
            model_name='tablech794',
            name='signature',
        ),
    ]
